# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mapas',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/mapas',
                'lib_path': 'mapas'},
  'syms': {'mapas.core': {'mapas.core.sumar_numeros': ('core.html#sumar_numeros', 'mapas/core.py')}}}
