# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mapas',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/mapas',
                'lib_path': 'mapas'},
  'syms': { 'mapas.core': { 'mapas.core.division': ('operaciones_basicas.html#division', 'mapas/core.py'),
                            'mapas.core.multiplicacion': ('operaciones_basicas.html#multiplicacion', 'mapas/core.py'),
                            'mapas.core.resta': ('operaciones_basicas.html#resta', 'mapas/core.py'),
                            'mapas.core.suma': ('operaciones_basicas.html#suma', 'mapas/core.py')},
            'mapas.prueba': {}}}
