# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['sumar_numeros']

# %% ../nbs/00_core.ipynb 3
def sumar_numeros(*args):
    """
    Suma una lista de números.

    Parameters:
    args (float): Números a sumar.

    Returns:
    float: Suma de los números proporcionados.
    """
    return sum(args)
