# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/prueba.ipynb.

# %% auto 0
__all__ = ['core']

# %% ../nbs/prueba.ipynb 3
import numpy as np
import importlib.util


from importlib.machinery import SourceFileLoader
core = SourceFileLoader("core",r"C:\Users\UFD\mapas-\mapas\core.py").load_module()

from core import PrecipitationMap, generate_fake_precipitation_data

