# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/prueba.ipynb.

# %% auto 0
__all__ = ['core']

# %% ../nbs/prueba.ipynb 2
import numpy as np
import importlib.util


from importlib.machinery import SourceFileLoader
core = SourceFileLoader("core","/Users/nightmare/mapas-/mapas/core.py").load_module()

from core import suma,resta,multiplicacion,division

