# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mapas-',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/mapas-',
                'lib_path': 'mapas_'},
  'syms': {'mapas_.core': {'mapas_.core.foo': ('core.html#foo', 'mapas_/core.py')}}}
